// Code generated by scripts/compile-sources.py; DO NOT EDIT.

package sources

import "github.com/geniusrabbit/adcorelib/adtype"

var amazonads = &adtype.SourceInfo{
	Name: "Amazon Ads",
	Description: "Amazon's advertising platform offering sponsored products, display, video, and programmatic DSP advertising with access to Amazon's first-party shopping and streaming audiences.",
	Domain: "advertising.amazon.com",
	IconURL: "https://advertising.amazon.com/favicon.ico",
	LogoURL: "https://m.media-amazon.com/images/G/01/advertising/AmazonAdsLogo.svg",
	URL: "https://advertising.amazon.com",
	DSPDomains: []string{"aax-us-east.amazon-adsystem.com", "aax-eu.amazon-adsystem.com"},
}
