// Code generated by scripts/compile-sources.py; DO NOT EDIT.

package sources

import "github.com/geniusrabbit/adcorelib/adtype"

// Sources is the list of all known RTB source descriptors.
var Sources = adtype.SourceInfoList{
	adMaven,
	adsterra,
	adxad,
	amazonads,
	clickaine,
	evadav,
	exoclick,
	facebookads,
	googleads,
	kadam,
	mgid,
	myadcash,
	popcash,
	propellerads,
	rollerads,
	taboola,
	trafficstars,
	twinred,
	yahooads,
	yandexads,
}
