// Code generated by scripts/compile-sources.py; DO NOT EDIT.

package sources

import "github.com/geniusrabbit/adcorelib/adtype"

var kadam = &adtype.SourceInfo{
	Name: "Kadam",
	Description: "Kadam is a CPC/CPM advertising network offering native ads, push notifications, banners, and teasers with advanced targeting including interests, geo, device, and retargeting across a broad publisher network.",
	Domain: "www.kadam.net",
	IconURL: "https://www.kadam.net/favicon.ico",
	LogoURL: "https://www.kadam.net/images/kadam-logo.svg",
	URL: "https://www.kadam.net",
	DSPDomains: []string{"rtb.kadam.net"},
}
