// Code generated by scripts/compile-sources.py; DO NOT EDIT.

package sources

import "github.com/geniusrabbit/adcorelib/adtype"

var mgid = &adtype.SourceInfo{
	Name: "MGID",
	Description: "MGID is a global native advertising platform delivering sponsored content, display, and video ads across a network of premium publishers with strong reach in North America, Europe, and Asia.",
	Domain: "www.mgid.com",
	IconURL: "https://www.mgid.com/favicon.ico",
	LogoURL: "https://www.mgid.com/images/mgid-logo.svg",
	URL: "https://www.mgid.com",
	DSPDomains: []string{"rtb.mgid.com"},
}
