// Code generated by scripts/compile-sources.py; DO NOT EDIT.

package sources

import "github.com/geniusrabbit/adcorelib/adtype"

var popcash = &adtype.SourceInfo{
	Name: "PopCash",
	Description: "PopCash is a global popunder advertising network offering high-volume traffic monetization with instant approval, real-time statistics, and targeting options including geo, device, and browser.",
	Domain: "www.popcash.net",
	IconURL: "https://www.popcash.net/favicon.ico",
	LogoURL: "https://www.popcash.net/images/popcash-logo.png",
	URL: "https://www.popcash.net",
	DSPDomains: []string{"rtb.popcash.net"},
}
