// Code generated by scripts/compile-sources.py; DO NOT EDIT.

package sources

import "github.com/geniusrabbit/adcorelib/adtype"

var propellerads = &adtype.SourceInfo{
	Name: "PropellerAds",
	Description: "PropellerAds is a large self-serve advertising network specializing in push notifications, popunders, native, and interstitial formats with global reach and performance-focused optimization.",
	Domain: "www.propellerads.com",
	IconURL: "https://www.propellerads.com/favicon.ico",
	LogoURL: "https://www.propellerads.com/images/propellerads-logo.svg",
	URL: "https://www.propellerads.com",
	DSPDomains: []string{"rtb-us.propellerads.com", "rtb-eu.propellerads.com"},
}
