// Code generated by scripts/compile-sources.py; DO NOT EDIT.

package sources

import "github.com/geniusrabbit/adcorelib/adtype"

var taboola = &adtype.SourceInfo{
	Name: "Taboola",
	Description: "Taboola is a leading native and content discovery advertising platform, powering recommendations across a global network of premium publishers with display, video, and sponsored content formats.",
	Domain: "www.taboola.com",
	IconURL: "https://www.taboola.com/favicon.ico",
	LogoURL: "https://www.taboola.com/images/taboola-logo.png",
	URL: "https://www.taboola.com",
	DSPDomains: []string{"rtb.taboola.com"},
}
