// Code generated by scripts/compile-sources.py; DO NOT EDIT.

package sources

import "github.com/geniusrabbit/adcorelib/adtype"

var trafficstars = &adtype.SourceInfo{
	Name: "TrafficStars",
	Description: "TrafficStars is a self-serve programmatic ad network specializing in adult and mainstream traffic, offering banner, native, push, video, and popunder formats with full OpenRTB integration.",
	Domain: "www.trafficstars.com",
	IconURL: "https://www.trafficstars.com/favicon.ico",
	LogoURL: "https://www.trafficstars.com/images/trafficstars-logo.svg",
	URL: "https://www.trafficstars.com",
	DSPDomains: []string{"*.tsyndicate.com"},
}
