// Code generated by scripts/compile-sources.py; DO NOT EDIT.

package sources

import "github.com/geniusrabbit/adcorelib/adtype"

var twinred = &adtype.SourceInfo{
	Name: "TwinRed",
	Description: "TwinRed is a programmatic advertising platform focused on adult and mainstream premium inventory, providing display, video, popunder, and native ad formats with OpenRTB/RTB support.",
	Domain: "www.twinred.com",
	IconURL: "https://www.twinred.com/favicon.ico",
	LogoURL: "https://www.twinred.com/images/twinred-logo.svg",
	URL: "https://www.twinred.com",
	DSPDomains: []string{"feed.ad.twinrdengine.com"},
}
