#!/usr/bin/env python3
"""Compile JSON source-info files into Go source files.

Usage:
    python3 scripts/compile-sources.py
    python3 scripts/compile-sources.py -in sources/data -out sources

Flags:
    -in   <dir>   source directory with JSON files  (default: sources/data)
    -out  <dir>   output directory for Go files      (default: sources)

Output:
    <out>/init.go       — var Sources = map[string]*adtype.SourceInfo{...}
    <out>/<name>.go     — one file per JSON source in <in>/
"""

import argparse
import json
import re
import sys
from pathlib import Path


REPO_ROOT    = Path(__file__).parent.parent
_DEFAULT_IN  = REPO_ROOT / "sources" / "data"
_DEFAULT_OUT = REPO_ROOT / "sources"

ADTYPE_PATH = "github.com/geniusrabbit/adcorelib/adtype"


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def to_go_ident(stem: str) -> str:
    """Convert a file stem (may contain hyphens) to a valid Go identifier."""
    parts = re.split(r"[-_]", stem)
    return parts[0] + "".join(p.capitalize() for p in parts[1:])


def go_string_slice(items: list[str]) -> str:
    if not items:
        return "nil"
    quoted = ", ".join(json.dumps(s) for s in items)
    return f"[]string{{{quoted}}}"


def go_value(v, indent: int = 0) -> str:
    """Recursively render a Python value as a Go literal."""
    tab   = "\t" * indent
    inner = "\t" * (indent + 1)

    if v is None:
        return "nil"
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, int):
        return str(v)
    if isinstance(v, float):
        return repr(v)
    if isinstance(v, str):
        return json.dumps(v)
    if isinstance(v, list):
        if not v:
            return "nil"
        lines = ["[]any{"]
        for item in v:
            lines.append(f"{inner}{go_value(item, indent + 1)},")
        lines.append(f"{tab}}}")
        return "\n".join(lines)
    if isinstance(v, dict):
        if not v:
            return "nil"
        lines = ["map[string]any{"]
        for k, val in v.items():
            lines.append(f"{inner}{json.dumps(k)}: {go_value(val, indent + 1)},")
        lines.append(f"{tab}}}")
        return "\n".join(lines)
    return "nil"


# ---------------------------------------------------------------------------
# File generators
# ---------------------------------------------------------------------------

def generate_source_file(stem: str, ident: str, data: dict) -> str:
    """Generate a single Go source file for one ad-network entry."""
    lines: list[str] = [
        "// Code generated by scripts/compile-sources.py; DO NOT EDIT.",
        "",
        "package sources",
        "",
        f'import "{ADTYPE_PATH}"',
        "",
        f"var {ident} = &adtype.SourceInfo{{",
    ]

    str_fields: list[tuple[str, str]] = [
        ("name",        "Name"),
        ("description", "Description"),
        ("domain",      "Domain"),
        ("icon_url",    "IconURL"),
        ("logo_url",    "LogoURL"),
        ("url",         "URL"),
    ]
    for json_key, go_field in str_fields:
        val = data.get(json_key)
        if val:
            lines.append(f"\t{go_field}: {json.dumps(val)},")

    dsp_domains = data.get("dsp_domains")
    if dsp_domains:
        lines.append(f"\tDSPDomains: {go_string_slice(dsp_domains)},")

    metadata = data.get("metadata")
    if metadata:
        lines.append(f"\tMetadata: {go_value(metadata, indent=1)},")

    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def generate_init_file(entries: list[tuple[str, str]]) -> str:
    """Generate sources/init.go with the Sources list."""
    lines: list[str] = [
        "// Code generated by scripts/compile-sources.py; DO NOT EDIT.",
        "",
        "package sources",
        "",
        f'import "{ADTYPE_PATH}"',
        "",
        "// Sources is the list of all known RTB source descriptors.",
        "var Sources = adtype.SourceInfoList{",
    ]
    for _, ident in sorted(entries, key=lambda e: e[0]):
        lines.append(f"\t{ident},")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Compile JSON source-info files into Go source files.",
    )
    parser.add_argument(
        "-in", dest="input", metavar="DIR",
        default=str(_DEFAULT_IN),
        help=f"source directory with JSON files (default: {_DEFAULT_IN})",
    )
    parser.add_argument(
        "-out", dest="output", metavar="DIR",
        default=str(_DEFAULT_OUT),
        help=f"output directory for Go files (default: {_DEFAULT_OUT})",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    data_dir   = Path(args.input)
    output_dir = Path(args.output)

    if not data_dir.exists():
        print(f"error: input directory not found: {data_dir}", file=sys.stderr)
        sys.exit(1)

    json_files = sorted(data_dir.glob("*.json"))
    if not json_files:
        print(f"error: no JSON files found in {data_dir}", file=sys.stderr)
        sys.exit(1)

    output_dir.mkdir(parents=True, exist_ok=True)

    entries: list[tuple[str, str]] = []
    for json_file in json_files:
        stem  = json_file.stem
        ident = to_go_ident(stem)
        entries.append((stem, ident))

        with open(json_file, encoding="utf-8") as f:
            data = json.load(f)

        go_code  = generate_source_file(stem, ident, data)
        out_path = output_dir / f"{stem}.go"
        out_path.write_text(go_code, encoding="utf-8")
        print(f"generated: {out_path}")

    init_code = generate_init_file(entries)
    init_path = output_dir / "init.go"
    init_path.write_text(init_code, encoding="utf-8")
    print(f"generated: {init_path}")


if __name__ == "__main__":
    main()
