// Code generated by rules/compile.py; DO NOT EDIT.

package rules

import (
	"github.com/geniusrabbit/adsource-openrtb/request/rtbrules"
)

// Rules maps RTB source names to their compiled rule sets.
var Rules = map[string]*rtbrules.RTBRules{
	"trafficstars": trafficstars,
	"twinred":      twinred,
}
