// Code generated by scripts/compile-rules.py; DO NOT EDIT.

package rules

import (
	"time"

	"github.com/geniusrabbit/adcorelib/platform/info"
	"github.com/geniusrabbit/adsource-openrtb/request/rtbrules"
)

var trafficstars = &rtbrules.RTBRules{
	Meta: rtbrules.Meta{
		Title:       "TrafficStars",
		Description: "RTB rules for TrafficStars ad network",
		Version:     "1.0.0",
		ModifiedAt:  time.Date(2026, 6, 20, 0, 0, 0, 0, time.UTC),
		Docs: []info.Documentation{
			{Title: "TrafficStars RTB Documentation", Link: "https://rtb-docs.trafficstars.com/"},
		},
	},
	Formats:             []string{"direct", "native", "video", "banner_300x250", "banner_300x100", "banner_315x300", "banner_900x250", "banner_728x90", "banner_250x150", "banner_305x99", "proxy", "proxy_300x250", "proxy_300x100", "proxy_315x300", "proxy_900x250", "proxy_728x90", "proxy_250x150", "proxy_305x99"},
	InterstitialFormats: []string{"proxy"},
	PushFormats:         []string{"native"},
	Rules: []*rtbrules.RuleItem{
		{
			Condition: rtbrules.Condition{
				Formats:      []string{"native"},
				Interstitial: rtbrules.Exclude,
				Push:         rtbrules.Include,
			},
			Config: rtbrules.RuleConfig{
				Ext: map[string]any{
					"type": "webpush",
				},
				NoRequestObject: true,
			},
			MapResponse: &rtbrules.MapResponse{
				Assets: []rtbrules.MapResponseAsset{
					{ID: 0, Name: "id", Field: "id"},
					{ID: 1, Name: "main", Field: "image"},
					{ID: 2, Name: "logo", Field: "icon"},
					{ID: 101, Name: "title", Field: "title"},
					{ID: 102, Name: "description", Field: "content"},
					{ID: 105, Name: "url", Field: "url"},
				},
			},
		},
	},
}
